import json
from typing import Any, Dict, List, Optional, Tuple
from uuid import uuid4

import requests
from langchain_core.output_parsers import JsonOutputParser
from langchain_core.prompts import ChatPromptTemplate

from app.core.config import settings
from app.core.constants import (
    DATASETS_USED,
    DATASETS_USED_ARG,
    INTERMEDIATE_MESSAGES,
    SQL_QUERIES_GENERATED,
    SQL_QUERIES_GENERATED_ARG,
    VISUALIZATION_RESULT,
    VISUALIZATION_RESULT_ARG,
)
from app.utils.model_registry.model_provider import get_llm_provider
from tests.test_config import TestConfig

from .terminal_formatter import TerminalFormatter

REQUEST_TIMEOUT = 120
trace_id = str(uuid4())


def setup_model():
    llm_provider = get_llm_provider(
        {
            "user": "e2e_test",
            "trace_id": trace_id,
            "chat_id": "e2e_test",
        }
    )
    return llm_provider.get_llm_model(settings.DEFAULT_LLM_MODEL)


def create_evaluation_chain():
    template = """You are a fair and intelligent data analyst assistant evaluating query responses using a numeric scoring system.

You will be given:
1. A comprehensive response object containing:
   - ai_response: The text response generated by our system
   - datasets_used: List of datasets identified and used
   - sql_queries_generated: List of SQL queries generated and executed
   - processing_steps: List of processing steps taken
   - visualization_results: Any visualization outputs (if applicable)
   - metadata: Summary counts of the above components
2. Details about the expected result (can be a string description or structured data)

generated_answer: {generated_answer}
expected_result: {expected_result}

The generated_answer is now a comprehensive object that includes:
- ai_response: The actual text response to evaluate
- datasets_used: Array of dataset IDs/names used in the analysis
- sql_queries_generated: Array of SQL queries executed
- processing_steps: Array of processing steps and intermediate messages
- visualization_results: Array of visualization outputs
- metadata: Object with counts (dataset_count, sql_query_count, etc.)

The expected_result may be:
- A string describing what the query should return (for comprehensive test cases)
- A structured object with specific criteria like dataset_identified, sql_query_count, visualization_needed, etc.

IMPORTANT EVALUATION PRINCIPLES:
1. DO NOT expect exact numerical values to match - the test cases use schema-based data, not real values
2. Focus on query approach, data structure, and result format rather than specific amounts or counts
3. Evaluate the COMPLETE response including datasets used, SQL queries, and processing approach, not just the text response
4. Check if the datasets_used array contains the expected datasets mentioned in the expected_result (Skip this step for single data type queries)
5. Verify if the sql_query_count matches expectations (if specified in expected_result)
6. Consider the processing_steps to understand if the right analytical approach was taken
7. For single dataset queries (Data Type: single): The SQL query was executed correctly and produced meaningful results, regardless of whether datasets_used is empty
8. For multi-dataset queries (Data Type: multi): The datasets_used array contains the expected multiple datasets

SCORING INSTRUCTIONS:
Provide a numeric score from 0-10 based on how well the response addresses the query.

Consider:
- Does the response correctly understand and address the user's question?
- Are the right datasets identified and used?
- Are the SQL queries appropriate for the task?
- Is the information provided accurate and relevant?
- Does the response format match what was requested?

Score based on overall quality and relevance:
- Higher scores (7-10): Response is accurate, relevant, and well-executed
- Mid scores (4-6): Response has the right idea but notable issues
- Lower scores (0-3): Response is incorrect, irrelevant, or fails to execute

Return the response as JSON object:
{{
    "evaluation_score": <numeric score 0-10>,
    "reasoning": "Brief explanation for the score - what was done well or what could be improved",
    "summary": "A brief one-line summary of the evaluation result"
}}"""

    prompt = ChatPromptTemplate.from_template(template)
    return prompt | setup_model() | JsonOutputParser()


def process_tool_calls(
    tool_calls: List[Dict[str, Any]],
) -> Tuple[List[str], List[str], List[str], List[str]]:
    tool_messages = []
    generated_sql_queries = []
    selected_datasets = []
    visualization_results = []

    if not tool_calls:
        return tool_messages, generated_sql_queries, selected_datasets, visualization_results

    for tool_call in tool_calls:
        if not tool_call or "function" not in tool_call:
            continue

        function_data = tool_call.get("function", {})
        name = function_data.get("name")

        try:
            args = json.loads(function_data.get("arguments", "{}"))

            if name == SQL_QUERIES_GENERATED:
                _extract_sql_queries(args, generated_sql_queries)

            elif name == DATASETS_USED:
                _extract_datasets(args, selected_datasets)

            elif name == VISUALIZATION_RESULT:
                _extract_visualization_results(args, visualization_results)

            elif name == INTERMEDIATE_MESSAGES and args.get("role") == "intermediate":
                content = args.get("content", "")
                category = args.get("category", "")
                tool_messages.append(content)

                if category == DATASETS_USED:
                    _extract_datasets_from_content(args, content, selected_datasets)

                if category == SQL_QUERIES_GENERATED:
                    _extract_sql_from_content(args, content, generated_sql_queries)

        except json.JSONDecodeError:
            continue

    return tool_messages, generated_sql_queries, selected_datasets, visualization_results


def _extract_sql_queries(args: Dict[str, Any], sql_queries: List[str]) -> None:
    if SQL_QUERIES_GENERATED_ARG in args and args.get(SQL_QUERIES_GENERATED_ARG):
        queries = args.get(SQL_QUERIES_GENERATED_ARG)
        if isinstance(queries, list):
            sql_queries.extend([str(q) for q in queries if q])
        elif queries:
            sql_queries.append(str(queries))


def _extract_datasets(args: Dict[str, Any], datasets: List[str]) -> None:
    if DATASETS_USED_ARG in args and args.get(DATASETS_USED_ARG):
        dataset_args = args.get(DATASETS_USED_ARG)
        if isinstance(dataset_args, list):
            datasets.extend(dataset_args)
        else:
            datasets.append(str(dataset_args))


def _extract_visualization_results(args: Dict[str, Any], visualization_results: List[str]) -> None:
    if VISUALIZATION_RESULT_ARG in args and args.get(VISUALIZATION_RESULT_ARG):
        viz_args = args.get(VISUALIZATION_RESULT_ARG)
        if isinstance(viz_args, list):
            visualization_results.extend([str(v) for v in viz_args if v])
        elif viz_args:
            visualization_results.append(str(viz_args))


def _extract_datasets_from_content(args: Dict[str, Any], content: str, datasets: List[str]) -> None:
    if "datasets" in args:
        _extract_datasets(args, datasets)
    elif ":" in content and any(
        keyword in content.lower() for keyword in ["using dataset", "selected dataset"]
    ):
        datasets_part = content.split(":", 1)[1].strip()
        datasets.append(datasets_part)


def _extract_sql_from_content(args: Dict[str, Any], content: str, sql_queries: List[str]) -> None:
    if "query" in args and args.get("query"):
        sql_queries.append(str(args.get("query")))
    elif "queries" in args:
        _extract_sql_queries(args, sql_queries)


def get_user_query(test_case: Dict[str, Any]) -> str:
    if "messages" in test_case:
        for message in test_case["messages"]:
            if message.get("role") == "user":
                return message.get("content", "")
    return test_case.get("query", "")


async def send_chat_request(test_case: Dict[str, Any], url: str) -> Dict[str, Any]:
    query_copy = test_case.copy()
    query_copy.pop("expected_result", None)

    try:
        headers = {
            "Content-Type": "application/json",
            "Accept": "text/event-stream",
            "X-organization-id": TestConfig.GOPIE_ORG_ID,
            "X-user-id": TestConfig.GOPIE_USER_ID,
        }
        response = requests.post(
            url,
            json={**query_copy, "chat_id": "", "trace_id": ""},
            headers=headers,
            stream=True,
            timeout=REQUEST_TIMEOUT,
        )
        response.raise_for_status()

        final_response = ""
        tool_messages = []
        generated_sql_queries = []
        selected_datasets = []
        visualization_results = []

        for line in response.iter_lines():
            if not line:
                continue

            decoded_line = line.decode("utf-8").strip()
            if not decoded_line.startswith("data:"):
                continue

            if decoded_line == "data: [DONE]":
                break

            try:
                chunk_data = json.loads(decoded_line[len("data: ") :])
                if "choices" in chunk_data and chunk_data["choices"]:
                    delta = chunk_data["choices"][0].get("delta", {})

                    if "content" in delta and delta["content"] is not None:
                        final_response += delta["content"] or ""

                    tool_calls = delta.get("tool_calls")
                    if tool_calls is not None:
                        msgs, queries, datasets, viz_results = process_tool_calls(tool_calls)
                        tool_messages.extend(msgs)
                        generated_sql_queries.extend(queries)
                        selected_datasets.extend(datasets)
                        visualization_results.extend(viz_results)
            except json.JSONDecodeError:
                continue

        return {
            "final_response": final_response,
            "tool_messages": tool_messages,
            "generated_sql_queries": generated_sql_queries,
            "selected_datasets": selected_datasets,
            "visualization_results": visualization_results,
        }

    except requests.exceptions.RequestException as e:
        return {"error": f"API request failed: {str(e)}"}


def initialize_test_results(user_query: str, expected_result: Any) -> Dict[str, Any]:
    """Initialize test results structure with proper handling of string expected results."""
    expected_sql_count = "Not specified"

    if isinstance(expected_result, dict):
        expected_sql_count = expected_result.get("sql_query_count", "Not specified")

    return {
        "query": user_query,
        "reasoning": "",
        "used_datasets": [],
        "sql_query_count": 0,
        "expected_dataset": "",
        "expected_sql_count": expected_sql_count,
        "status": "error",
        "evaluation_score": 0,
    }


def handle_expected_error(
    results: Dict[str, Any], formatter: Optional[TerminalFormatter]
) -> Dict[str, Any]:
    results.update(
        {
            "evaluation": {"note": "Expected error test case - passed"},
            "status": "success",
            "evaluation_score": 10,
        }
    )
    if formatter:
        formatter.print_success("Expected error test completed successfully")
    return results


def update_results_with_evaluation(
    results: Dict[str, Any],
    evaluation: Dict[str, Any],
    response: Dict[str, Any],
    expected_result: Any,  # Can be string or dict
    formatter: Optional[TerminalFormatter],
) -> None:
    results.update(
        {
            "reasoning": evaluation.get("reasoning", "No reasoning provided"),
            "used_datasets": response["selected_datasets"],
            "sql_query_count": len(response["generated_sql_queries"]),
            "response": response,
            "evaluation": evaluation,
        }
    )

    # Handle dataset identification for dict-based expected results
    if isinstance(expected_result, dict) and "dataset_identified" in expected_result:
        results["expected_dataset"] = expected_result["dataset_identified"]
    else:
        results["expected_dataset"] = "Not applicable for single dataset case"

    # Use numeric score (0-10) - save score, display based on thresholds
    score = evaluation.get("evaluation_score", 0)
    results["evaluation_score"] = score

    # Display formatting based on score thresholds (not saved to JSON)
    if score >= 8:
        results["status"] = "success"
        if formatter:
            formatter.print_test_result("passed")
    elif score >= 5:
        results["status"] = "success"
        if formatter:
            formatter.print_test_result("partial", results["reasoning"])
    else:
        results["status"] = "error"
        if formatter:
            formatter.print_test_result("failed", results["reasoning"])
