[project]
name = "livekit-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "livekit-agents>=0.12.17",
    "livekit-plugins-openai>=0.11.3",
    "livekit-plugins-silero>=0.7.5",
    "python-dotenv>=1.0.1",
]
