project_name: gopie

builds:
- id: gopie
  binary: gopie
  env:
  - CGO_ENABLED=1
  - CC=aarch64-linux-gnu-gcc
  # - GO386=softfloat
  goos:
  - linux
  # goarch:
  #   - amd64

archives:
  - id: gopie
    builds:
      - gopie
    name_template: "gopie_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
- dockerfile: Dockerfile
  image_templates:
    - "asia-south1-docker.pkg.dev/factly-prod/gopie/gopie:{{ .Tag }}"
  use: docker
  # build_flag_templates:
  # - "--platform=linux/amd64"

docker_manifests:
  -
    image_templates:
    - "asia-south1-docker.pkg.dev/factly-prod/gopie/gopie:{{ .Version }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'