version: 2

project_name: gopie

builds:
- id: gopie
  binary: gopie
  env:
  - CGO_ENABLED=1 # changed from 0 to 1 ref: https://github.com/marcboeker/go-duckdb/issues/199#issuecomment-2107614112
  - GO386=softfloat
  - GOARCH=amd64
  - CC=aarch64-linux-gnu-gcc
  goos:
  - linux
  ignore:
    - goos: windows
      goarch: arm
  # goarch:
  #   - amd64

# archives:
#   - id: gopie
#     builds:
#       - gopie
#     name_template: "gopie_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
- dockerfile: Dockerfile
  image_templates:
    - "asia-south1-docker.pkg.dev/factly-prod/gopie/gopie:{{ .Tag }}"
    - "asia-south1-docker.pkg.dev/factly-prod/gopie/gopie:latest"

  use: buildx
  build_flag_templates:
  - "--platform=linux/amd64"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

