services:
  gopie:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ./dataful:/duckdb
    networks:
      - gopie

networks:
  gopie:
