services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_api:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gopie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - gopie

  gopie-web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    env_file:
      - ./config-noauth.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - gopie

  companion:
    image: transloadit/companion:sha-e80a7f7
    ports:
      - "3020:3020"
    env_file:
      - ./config-noauth.env
    networks:
      - gopie
    depends_on:
      - rustfs

  gopie-migrate:
    build:
      context: ./server
      dockerfile: Dockerfile.migrate
    environment:
      - GOOSE_DBSTRING=postgres://postgres:postgres@postgres:5432/gopie?sslmode=disable
      - GOOSE_DRIVER=postgres
      - GOOSE_MIGRATION_DIR=migrations
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gopie

  gopie-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./config-noauth.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./volumes/duckdb:/home/gopie/dataful
    networks:
      - gopie
    user: "0:0"
    command: >
      sh -c "chown -R 1001:1001 /home/gopie/dataful && 
             chmod -R 755 /home/gopie/dataful && 
             su -s /bin/sh gopie -c 'cd /home/gopie && gopie serve'"

  rustfs:
    image: rustfs/rustfs:latest
    restart: always
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # RustFS Console
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_ADDRESS=:9000
    volumes:
      - ./volumes/rustfs/data:/data
    networks:
      - gopie

  create-buckets:
    image: amazon/aws-cli:latest
    depends_on:
      - rustfs
    environment:
      - AWS_ACCESS_KEY_ID=rustfsadmin
      - AWS_SECRET_ACCESS_KEY=rustfsadmin
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - gopie
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      aws s3 mb s3://gopie --endpoint-url http://rustfs:9000 || true;
      aws s3 mb s3://downloads --endpoint-url http://rustfs:9000 || true;
      echo 'Buckets created successfully';
      exit 0;
      "

include:
  - ./chat-server/docker-compose.yaml

networks:
  gopie:
    name: gopie-noauth
    driver: bridge
