services:
  write:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./volumes/write:/home/gopie/data
    environment:
      - GOPIE_DUCKDB_DSN=./data/main.db
      - GOPIE_LOG_LEVEL=debug
      - GOPIE_LOG_OUTPUT=stdout
      - GOPIE_APPLICATION_MODE=dev
      - GOPIE_MASTER_KEY=masterkey
      - GOPIE_SERVER_PORT=8000
      - GOPIE_DUCKDB_DSN=./data/main.db
      - GOPIE_DUCKDB_MEMORY_LIMIT=1
      - GOPIE_BBOLT_PATH=./auth_bblot.db
      - GOPIE_OPEN_AI_API_KEY=[REMOVED]
      - GOPIE_S3_ACCESS_KEY=miniokey
      - GOPIE_S3_SECRET_ACCESS_KEY=miniosecret
      - GOPIE_S3_ENDPOINT=http://localhost:9000
      - GOPIE_GOPIE_SERVER_URL=http://localhost:8000
      - GOPIE_SERVER_READ_ONLY=false
    networks:
      - gopie
  read-1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    volumes:
      # - .:/app
      - ./volumes/read:/home/gopie/data
    environment:
      - GOPIE_DUCKDB_DSN=./data/main.db
      - GOPIE_LOG_LEVEL=debug
      - GOPIE_LOG_OUTPUT=stdout
      - GOPIE_APPLICATION_MODE=dev
      - GOPIE_MASTER_KEY=masterkey
      - GOPIE_SERVER_PORT=8000
      - GOPIE_DUCKDB_DSN=./data/main.db
      - GOPIE_DUCKDB_MEMORY_LIMIT=1
      - GOPIE_BBOLT_PATH=./auth_bblot.db
      - GOPIE_OPEN_AI_API_KEY=[REMOVED]
      - GOPIE_S3_ACCESS_KEY=miniokey
      - GOPIE_S3_SECRET_ACCESS_KEY=miniosecret
      - GOPIE_S3_ENDPOINT=http://localhost:9000
      - GOPIE_GOPIE_SERVER_URL=http://localhost:8000
      - GOPIE_SERVER_READ_ONLY=true
    networks:
      - gopie

  read-2:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    volumes:
      - ./volumes/read:/home/gopie/data
    environment:
      - GOPIE_DUCKDB_DSN=./data/main.db
      - GOPIE_LOG_LEVEL=debug
      - GOPIE_LOG_OUTPUT=stdout
      - GOPIE_APPLICATION_MODE=dev
      - GOPIE_MASTER_KEY=masterkey
      - GOPIE_SERVER_PORT=8000
      - GOPIE_DUCKDB_DSN=./data/main.db
      - GOPIE_DUCKDB_MEMORY_LIMIT=1
      - GOPIE_BBOLT_PATH=./auth_bblot.db
      - GOPIE_OPEN_AI_API_KEY=[REMOVED]
      - GOPIE_S3_ACCESS_KEY=miniokey
      - GOPIE_S3_SECRET_ACCESS_KEY=miniosecret
      - GOPIE_S3_ENDPOINT=http://localhost:9000
      - GOPIE_GOPIE_SERVER_URL=http://localhost:8000
      - GOPIE_SERVER_READ_ONLY=true
    networks:
      - gopie
  #########################################################################
  #####                        MINIO                                #######
  #########################################################################
  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/minio/data:/data
    environment:
      - MINIO_ROOT_USER=miniokey
      - MINIO_ROOT_PASSWORD=miniosecret
    networks:
      - gopie
    # command: server /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - gopie
    entrypoint: >
      /bin/sh -c " apk add --no-cache bash; wait-for-it.sh minio:9000 -- echo 'Minio is up. Creating the bucket!!'; /usr/bin/mc config host add myminio http://minio:9000 miniokey miniosecret; /usr/bin/mc mb myminio/gopie; /usr/bin/mc anonymous set public myminio/gopie; exit 0; "
 
networks:
  gopie:

volumes: 
  volumes:
