services:
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./app:/code/app
    env_file:
      - ./.env
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    depends_on:
      - qdrant
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gopie
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ../volumes/qdrant:/qdrant/storage
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - gopie
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# AI Gateway Services
include:
  - ./gateways/portkey/docker-compose.yml
  - ./gateways/litellm/docker-compose.yml
