{{- if .Values.web.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "web.name" . }}-pdb
  namespace: {{ include "gopie.namespace" . }}
  labels:
    {{ include "web.labels" . | nindent 4 }}
spec:
  {{- if .Values.web.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.web.podDisruptionBudget.minAvailable }}
  {{- else if .Values.web.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.web.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{ include "web.selectorLabels" . | nindent 6 }}
{{- end }}