---
config:
  flowchart:
    curve: basis
---
graph TD;
	__start__([<p>__start__</p>]):::first
	choose_visualization(choose_visualization)
	format_data_for_visualization(format_data_for_visualization)
	__end__([<p>__end__</p>]):::last
	__start__ --> choose_visualization;
	choose_visualization --> format_data_for_visualization;
	format_data_for_visualization --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
