apiVersion: v2
name: gopie
description: A comprehensive Helm chart for deploying Gopie - an AI-powered data analysis and chat platform
home: https://github.com/factly/gopie
sources:
  - https://github.com/factly/gopie
keywords:
  - ai
  - data-analysis
  - chat
  - analytics
  - self-hosted
maintainers:
  - name: Factly
    url: https://factly.in

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.2"
dependencies: 
  - name: postgresql
    version: 15.5.2  # Use the version you want
    repository: https://charts.bitnami.com/bitnami
  - name: minio
    version: 17.0.13  # Use the version you want
    repository: https://charts.bitnami.com/bitnami

  - name: companion
    version: 0.1.10
    repository: https://factly.github.io/helm-charts

  - name: qdrant
    version: 1.12.5
    repository: https://qdrant.github.io/qdrant-helm

