---
config:
  flowchart:
    curve: basis
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor(supervisor)
	multidataset_agent(multidataset_agent)
	single_dataset_agent(single_dataset_agent)
	visualizer_agent(visualizer_agent)
	visualization_supervisor(visualization_supervisor)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor;
	multidataset_agent --> visualization_supervisor;
	single_dataset_agent --> visualization_supervisor;
	supervisor -.-> multidataset_agent;
	supervisor -.-> single_dataset_agent;
	visualization_supervisor -.-> __end__;
	visualization_supervisor -.-> visualizer_agent;
	visualizer_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
