---
config:
  flowchart:
    curve: basis
---
graph TD;
	__start__([<p>__start__</p>]):::first
	validate_input(validate_input)
	stream_invalid_response(stream_invalid_response)
	process_context(process_context)
	supervisor(supervisor)
	multi_dataset_agent(multi_dataset_agent)
	single_dataset_agent(single_dataset_agent)
	visualization_agent(visualization_agent)
	check_visualization(check_visualization)
	generate_result(generate_result)
	query_router(query_router)
	__end__([<p>__end__</p>]):::last
	__start__ --> process_context;
	__start__ --> validate_input;
	check_visualization --> query_router;
	multi_dataset_agent -.-> generate_result;
	multi_dataset_agent -.-> visualization_agent;
	process_context --> check_visualization;
	query_router -. &nbsp;invalid&nbsp; .-> stream_invalid_response;
	query_router -. &nbsp;valid&nbsp; .-> supervisor;
	single_dataset_agent -.-> generate_result;
	single_dataset_agent -.-> visualization_agent;
	supervisor -.-> multi_dataset_agent;
	supervisor -.-> single_dataset_agent;
	supervisor -.-> visualization_agent;
	validate_input --> query_router;
	generate_result --> __end__;
	stream_invalid_response --> __end__;
	visualization_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
