name: Server Release CI
on:
  release:
    types: [released]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Use Go
        uses: actions/setup-go@v2
        id: setup_go
        with:
          go-version: "1.22.6"
      - name: Cache go-modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/735814365928/locations/global/workloadIdentityPools/ga-google-artifact-registry/providers/github
          service_account: ga-google-artifact-registry@factly-prod.iam.gserviceaccount.com
          access_token_lifetime: 1800s          
      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-south1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          
      - name: Build and push Gopie Web
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: asia-south1-docker.pkg.dev/factly-prod/gopie/gopie:${{ env.RELEASE_VERSION }}
          file: Dockerfile

      # - name: Run GoReleaser
      #   uses: goreleaser/goreleaser-action@v6
      #   with:
      #     distribution: goreleaser
      #     version: '~> v2'
      #     args: release --clean --skip=validate
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}