name: Server Release CI
on:
  push:
    tags:
      - '*'
jobs:
  build-server:
    uses: factly/gopie-ee/.github/workflows/docker-build-push.yaml@develop
    with:
      tags: asia-south1-docker.pkg.dev/factly-prod/gopie/server:${{ github.ref_name }}
      context: server
      dockerfile: server/Dockerfile
    permissions:
      contents: read
      id-token: write

  build-migrate:
    uses: factly/gopie-ee/.github/workflows/docker-build-push.yaml@develop
    with:
      tags: asia-south1-docker.pkg.dev/factly-prod/gopie/migrate:${{ github.ref_name }}
      context: server
      dockerfile: server/Dockerfile.migrate
    permissions:
      contents: read
      id-token: write
