name: gopie-web-app - Docker Build and Push CI
on:
  push:
    tags:
      - '*'

jobs:
  release:
    uses: factly/gopie-ee/.github/workflows/docker-build-push.yaml@develop
    with:
      tags: asia-south1-docker.pkg.dev/factly-prod/gopie/web:${{ github.ref_name }}
      context: web
      dockerfile: web/Dockerfile.prod
    permissions:
      contents: read
      id-token: write
