FROM node:18-alpine

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install bun
RUN apk add --no-cache unzip curl bash && \
    curl -fsSL https://bun.sh/install | bash && \
    ln -s $HOME/.bun/bin/bun /usr/local/bin/bun

# Copying source files
COPY . /app

# Installing dependencies
RUN bun install --frozen-lockfile

# Running the app
CMD ["bun", "dev"]
